### ISSUE TITLE
调用onstop后, onrecording还会继续调用一次

### ISSUE THREAD

**Issue by badboy-tian** [SheTieJun/Mp3Recorder#1]
![image](https://user-images.githubusercontent.com/2835129/87390944-653a0680-c5dc-11ea-87a2-e956098c9022.png)

**Comment by badboy-tian** [comment]
这样导致我在onsuccess里面做的操作被覆盖了

**Comment by SheTieJun** [comment]
> 这样导致我在onsuccess里面做的操作被覆盖了

这个是我的失误 ，改是不难，是否可以知道你是在`onRecording`  和 `onSuccess`  做了什么操作吗？防止改错了，我需要知道具体是什么场景，正常它们是不会有冲突的，就像我的demo~ 

Lame 输出的是支持边录边播的数据格式，所以我在`stop()`的时候，只是改了Flag：`isRecording = false` ，就把录制的文件地址抛出去了，而不是在`AudioRecord` .`release() `去`onsuccess` ，因此**录音线程**可能会再执行一次`while`

**Comment by badboy-tian** [comment]
我在onRecording里面更新录制时间, tvTime.text = "时间: xx:xx"
在onSuccess里面, tvTime.text = "点击开始"

这个无所谓了, 我用了两个textview分别显示 这样就不冲突了

我现在遇到另外一个问题

我正在录制, 然后暂停.  这个时候我想重录的话.
调用onReset, 然后onStart? 这样会报错

**Comment by SheTieJun** [comment]
> 我在onRecording里面更新录制时间, tvTime.text = "时间: xx:xx"
> 在onSuccess里面, tvTime.text = "点击开始"
> 
> 这个无所谓了, 我用了两个textview分别显示 这样就不冲突了
> 
> 我现在遇到另外一个问题
> 
> 我正在录制, 然后暂停. 这个时候我想重录的话.
> 调用onReset, 然后onStart? 这样会报错

`onReset` 如果所有数据置空，你有重新设置保存的文件路径

**Comment by badboy-tian** [comment]
```
saveFile = if (TextUtils.isEmpty(file)) {
            val mRecordFile = getSaveFilePath()
            mRecordFile
        } else {
            file
        }
        mRecorder.setOutputFile(saveFile)
        mRecorder.start()
```

暂停状态下,  调用start  感觉好像是resume方法被调用了一样, 没不是重新开始, 而是继续

**Comment by badboy-tian** [comment]
所以要完成重新录, 需要这样写?
```
mRecorder.onReset()
mRecorder.setOutputFile(saveFile)
mRecorder.start()
```

**Comment by badboy-tian** [comment]
在暂停状态下, 好像这样写  也会报错

**Comment by SheTieJun** [comment]
> ```
> saveFile = if (TextUtils.isEmpty(file)) {
>             val mRecordFile = getSaveFilePath()
>             mRecordFile
>         } else {
>             file
>         }
>         mRecorder.setOutputFile(saveFile)
>         mRecorder.start()
> ```
> 
> 暂停状态下, 调用start 感觉好像是resume方法被调用了一样, 没不是重新开始, 而是继续

上面只能用在开始录制，建议你运行一下demo ，在具体场景下查看一下demo的实现方式 
[MixRecordUtils](https://github.com/SheTieJun/Mp3Recorder/blob/master/app/src/main/java/me/shetj/mp3recorder/record/utils/MixRecordUtils.kt)

```
    fun startOrPause(file :String = "") {
        if (mRecorder == null) {
            initRecorder()
        }
        when (mRecorder?.state) {
            RecordState.STOPPED -> {
            //如果是停止状态 开始录制
                if (TextUtils.isEmpty(file)) {
                    val mRecordFile = SDCardUtils.getPath("record") + "/" + System.currentTimeMillis() + ".mp3"
                    this.saveFile = mRecordFile
                }else{
                    this.saveFile = file
                }
                mRecorder?.onReset()
                mRecorder?.setOutputFile(saveFile,!TextUtils.isEmpty(file))
                mRecorder?.start()
            }
            RecordState.PAUSED -> {
            //如果暂停，就继续录制
                mRecorder?.onResume()
            }
            RecordState.RECORDING -> {
            //如果正在录制就暂停
                mRecorder?.onPause()
            }
        }
    }
```

**Comment by SheTieJun** [comment]
> 在暂停状态下, 好像这样写 也会报错

刚没看到，如果还有问题，加我QQ? 我需要看下你怎么写的，因为这个项目我是根据自己的使用场景写了，所有有些场景我没有考虑到。

**Comment by badboy-tian** [comment]
刚刚试了下只要onReset后不立马调用start() 就没问题

那个背景音乐我好像没有搞懂意思.  是边播放音乐边录? 还是说直接把背景音乐和录音合成一段mp3?

如果是边播放边录的话, 这样背景音乐效果不好的 有可能被消音

**Comment by SheTieJun** [comment]
MixRecorder  是读取背景音乐的PCM  和 录制的PCM 进行合成的，所有只要你设置合成的声音大小，你就可以静音都可以，所有也支持耳机
MP3Recorder 是边播边录，这个就必须外放音乐

**Comment by SheTieJun** [comment]
> 刚刚试了下只要onReset后不立马调用start() 就没问题
> 
> 那个背景音乐我好像没有搞懂意思. 是边播放音乐边录? 还是说直接把背景音乐和录音合成一段mp3?
> 
> 如果是边播放边录的话, 这样背景音乐效果不好的 有可能被消音

这个注意看文档，MixRecorder 录音的参数必须和背景音乐一样
例如设置单声道，播放的背景是双声道，合成和播放都会让背景音乐拉长；反之双声音录制，背景音乐是单声音，播放节奏会变快，通知合成时背景音乐的节奏也会超级快

**Comment by badboy-tian** [comment]
大佬 QQ多少 我咨询下事儿呢  我QQ 212805899

**Comment by SheTieJun** [comment]
> 大佬 QQ多少 我咨询下事儿呢 我QQ 212805899

你加我吧  375105540  ，不过我不是大佬~，所有可能无法解决你的问题
