### ISSUE TITLE
Failed to resolve: com.github.SheTieJun:Mp3Recorder:+

### ISSUE THREAD

**Issue by hanilala** [SheTieJun/Mp3Recorder#2]
Android studio 4.0 ，添加依赖的时候提示 Failed to resolve: com.github.SheTieJun:Mp3Recorder:+

**Comment by SheTieJun** [comment]
> Android studio 4.0 ，添加依赖的时候提示 Failed to resolve: com.github.SheTieJun:Mp3Recorder:+
+ 我是想表示最新的意思，你需要写成  “com.github.SheTieJun:Mp3Recorder:0.0.12”

**Comment by SheTieJun** [comment]
> Android studio 4.0 ，添加依赖的时候提示 Failed to resolve: com.github.SheTieJun:Mp3Recorder:+

    maven { url 'https://jitpack.io'  }   有加jitpack的仓库？

**Comment by hanilala** [comment]
> > Android studio 4.0 ，添加依赖的时候提示 Failed to resolve: com.github.SheTieJun:Mp3Recorder:+
> 
> ```
> maven { url 'https://jitpack.io'  }   有加jitpack的仓库？
> ```

谢谢解答，我加了 maven { url 'https://jitpack.io'  } ，改成最新的 0.0.12 还是不行哦

**Comment by SheTieJun** [comment]
> > > Android studio 4.0 ，添加依赖的时候提示 Failed to resolve: com.github.SheTieJun:Mp3Recorder:+
> > 
> > 
> > ```
> > maven { url 'https://jitpack.io'  }   有加jitpack的仓库？
> > ```
> 
> 谢谢解答，我加了 maven { url 'https://jitpack.io' } ，改成最新的 0.0.12 还是不行哦

正常应该可以下载的 ，build是成功的 ： https://jitpack.io/#SheTieJun/Mp3Recorder/0.0.12    
你检查一下尝试一下其他你没下过的库试试，可能是抽风了？或者需要代理？

**Comment by SheTieJun** [comment]
![QQ截图20200818152105](https://user-images.githubusercontent.com/17263560/90482938-8f945c00-e166-11ea-958e-7290d706cf0a.png)
我试了一下可以下载成功

**Comment by hanilala** [comment]
> ![QQ截图20200818152105](https://user-images.githubusercontent.com/17263560/90482938-8f945c00-e166-11ea-958e-7290d706cf0a.png)
> 我试了一下可以下载成功

刚刚又试了，可以了，感谢耐心解答
