### ISSUE TITLE
录音音量

### ISSUE THREAD

**Issue by Bruce8hou** [SheTieJun/Mp3Recorder#6]
您好，在录音的时候，能否提供一个录音音量调节的接口 或者提供一些增益开关，因为在部分手机上录音声音偏小

**Comment by SheTieJun** [comment]
> 您好，在录音的时候，能否提供一个录音音量调节的接口 或者提供一些增益开关，因为在部分手机上录音声音偏小

 //设置增强系数(不建议修改，因为会产生噪音~,细小的噪音放大就是噪音)
  `fun setWax(wax: Float)`
这个方法可以增强声音。
也可以在创建的时候就是设置    
 ```
mRecorder = recorder {
          mMaxTime = 5 * 60 * 1000
          wax = 1f  //设置声音增强系数(不建议修改，因为会产生噪音~,细小的噪音放大就是噪音)
          samplingRate = 44100
          audioSource = BaseRecorder.AudioSource.MIC
          audioChannel = BaseRecorder.AudioChannel.STEREO
      }.buildMix(Utils.app)
```

**Comment by Bruce8hou** [comment]
![1679240787553](https://user-images.githubusercontent.com/20390458/226187619-a42635fb-0201-4a74-a807-88c356e9b3cd.png)
设置了 但是音量没有明显增加 是不是还有其他什么条件才会生效呢

**Comment by SheTieJun** [comment]
> ![1679240787553](https://user-images.githubusercontent.com/20390458/226187619-a42635fb-0201-4a74-a807-88c356e9b3cd.png) 设置了 但是音量没有明显增加 是不是还有其他什么条件才会生效呢

额 太久没用过这个参数，我自己都忘记了。 不过不要超过1.5f吧

**Comment by SheTieJun** [comment]
你用的是MixRecorder吧？SimRecorder有些功能后面没有去实现了

**Comment by Bruce8hou** [comment]
我用的就是SimRecorder  我换MixRecorder试一试哈

**Comment by SheTieJun** [comment]
嗯，MixRecorder不用背景音乐也可以使用的~
这个增强参数后面我没去用了，所有就没有去管它了，后面是通过FFmpeg去增强~
如果还是不行，我可能需要一些时间去调试一下~

**Comment by Bruce8hou** [comment]
你好 测试了 都没有太大的效果。麻烦调试一下哦。还有没有更好的增益方法呢

**Comment by SheTieJun** [comment]
![image](https://user-images.githubusercontent.com/17263560/226233393-b3ffb3b9-3dfd-4fda-bae5-e324d72632c2.png)

我看了是有用的 我这个设置的是5f,
虽然可以增强声音，但是这种方法很容易让声音失真。

**Comment by Bruce8hou** [comment]
我只是有部分测试机硬件比较弱，录音声音偏小，用了max 声音音量没有明显增加，但是我没有去获取数据对比 只是感官上的，目前除了调用max  还有没有其他的增益的方式呢

**Comment by Bruce8hou** [comment]
好的 能不能在录音pcm数据打包前给一个拦截器接口呢 ，这样可以做一些额外的数据操作

**Comment by SheTieJun** [comment]
可以，不难~ 不过需要一些时间，因为我的录音的里面pcm,有short、byte数据类型不一样，我需要时间统一一下

**Comment by Bruce8hou** [comment]
非常感谢
