### ISSUE TITLE
录音原始数据 byte[] 回调增加

### ISSUE THREAD

**Issue by longxuewei** [SheTieJun/Mp3Recorder#8]
在录音的时候是否可以将原始录制的数据 byte[] 回调呢？ 有个需求就是拿到原始数据做可视化音频振幅绘制。所以麻烦大佬增加一下可否！

**Comment by SheTieJun** [comment]
没有必要新增，short 和byte是可以相互转换的

**Comment by longxuewei** [comment]
好的，意思我可以从 PCMListener.onBeforePCMToMp3 方法的回调中拿到 short[] 并将其转换成 byte[] 使用吗？

**Comment by SheTieJun** [comment]
是的

**Comment by longxuewei** [comment]
好的，感谢！😁
