### ISSUE TITLE
支持保存wav格式吗

### ISSUE THREAD

**Issue by lishangwl** [SheTieJun/Mp3Recorder#9]
支持保存wav格式吗

**Comment by SheTieJun** [comment]
当前库核心功能是输出MP3。目前没有支持。
wav 本质是PCM,只是加了哥头~,等于不用Lame转MP3~。但是就和我这个库的核心功能起冲突了。

你这个需求等于不需要我这个库才对。~ 如果你非要用，有2个方法：
1. 在PCMListener.onBeforePCMToMp3，回调的时候，把PCM保存成wav,网上方法很多
2. copy一下，重写一下你使用的Recorder的EncodeThread，把PCM直接保存成Wav

**Comment by lishangwl** [comment]
> 当前库核心功能是输出MP3。目前没有支持。 wav 本质是PCM,只是加了哥头~,等于不用Lame转MP3~。但是就和我这个库的核心功能起冲突了。
> 
> 你这个需求等于不需要我这个库才对。~ 如果你非要用，有2个方法：
> 
> 1. 在PCMListener.onBeforePCMToMp3，回调的时候，把PCM保存成wav,网上方法很多
> 2. copy一下，重写一下你使用的Recorder的EncodeThread，把PCM直接保存成Wav

好的，谢谢。
